### ISSUE TITLE
Loot Sheet won't open after update 3.2.1

### ISSUE THREAD

**Issue by BigTug** [Almightygir/fvtt-loot-sheet-npc-pf1#1]

**Comment by BigTug** [comment]
Can not open merchant sheet from actors tab.

**Comment by BigTug** [comment]
When I open the Sheet Configuration most of the options under Default Sheet are gone. Only option is Default Token Sheet. Because of this cannot access existing Merchants. 
If I create a new actor I do get the PF1.LootSheetPf1NPC option.

**Comment by Almightygir** [comment]
Hi @BigTug 

Could you confirm if you're having trouble opening a merchant sheet as a GM or as a player, please?

**Comment by Almightygir** [comment]
I've narrowed the issue down, it's a problem with containers. Working on a fix.

**Comment by Almightygir** [comment]
https://github.com/Almightygir/fvtt-loot-sheet-npc-pf1/releases/tag/v3.2.2

This should resolve your issue!

**Comment by Almightygir** [comment]
Closing issue as resolved after no further contact was made.
